### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by exotexot** [mvanroon/react-native-axios-jwt#22]
npm install react-native-axios-jwt@1.7.0

npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-axios-jwt@1.7.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by exotexot** [comment]
npm install react-native-axios-jwt

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cat@0.0.1
npm ERR! Found: axios@0.27.2
npm ERR! node_modules/axios
npm ERR!   axios@"0.27.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.21.1" from react-native-axios-jwt@1.6.0
npm ERR! node_modules/react-native-axios-jwt
npm ERR!   react-native-axios-jwt@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by mvanroon** [comment]
Should be fixed in 1.7.1
