### ISSUE TITLE
[AxiosError: Unable to refresh access token for request due to token refresh error: Request failed with status code 400]

### ISSUE THREAD

**Issue by Doc-Code** [mvanroon/react-native-axios-jwt#23]

**Comment by mvanroon** [comment]
Please make an effort when creating issues. You didn't even include a description.

Your 400 error comes from your backend. Inspect your network.

**Comment by Doc-Code** [comment]
@mvanroon
I'm sorry. 
Sent incorrect data to the server. I'm just tired of looking for a mistake for a very long time. 
The server accepted {refresh: refreshToken}, and the default library was {token: refreshToken}
