### ISSUE TITLE
isLoggedIn is always logged in, even when tokens are undefined or null.

### ISSUE THREAD

**Issue by programadoracoriano** [mvanroon/react-native-axios-jwt#27]
Hello there,
i am here to tell you that the isLoggedIn() function is always true, even with empty or undefined tokens.

**Comment by omarlahkim** [comment]
I assume the project is so old it needs to be updated

**Comment by mvanroon** [comment]
My apologies for the late response. I just tested this and I cannot reproduce this. Unit tests also work as expected:

https://github.com/mvanroon/react-native-axios-jwt/blob/main/tests/isLoggedIn.test.ts

Can you double check that you removed the tokens before checking isLoggedIn?
