### ISSUE TITLE
Sending empty request

### ISSUE THREAD

**Issue by wecoon** [mvanroon/react-native-axios-jwt#5]
Changing the issue to the one I currently have :)

I've managed to make it run, kind of. However, login post request is sending empty request, It seems to be this lib specific, but not sure. 

```
  const handleLogin = async (email, password) => {
    const response = await axiosInstance.post('/auth/token/obtain/', {
      email: email,
      password: password,
    });
    await setAuthTokens({
      accessToken: response.data.access_token,
      refreshToken: response.data.refresh_token,
    });
  };
```

**Comment by mvanroon** [comment]
Perhaps email and password are undefined?

axiosInstance is not part of this library, so I don't see how your issue is related to this lib.
